# 大數據分析應用期中考試題

## 姓名: 陳奕達
## 學號: Q08300982

<hr style="border-color: brown; border-width: 3px">

## 一、第一大題 (40 %) 
### 請連結上內政部人口生育死亡婚姻數據網頁 (點選<a href='https://data.gov.tw/dataset/131138'>這裡</a>)，請使用 <u>10911各村（里）人口統計月報表（含同婚）</u> 資料集。

### 第 1-1 題: 目前 `population`資料框是英文名稱，而第 0 筆資料是中文名稱。請將欄位名稱更換第 0 筆的中文名稱。

### 第 1-2 題: 從 population 資料框的第 4 個欄位 (出生數) 一直到最後一個欄位在目前都是 object 的資料型態，請將這些欄位轉換為 int，完成後請用 `dtypes`顯示結果。

### Solution 1-1

In [2]:
import pandas as pd

In [61]:
population = pd.read_csv('./data/opendata10911M013.csv')

alist=[]
for i in population.columns:          #欄位名稱更換為中文
    i=population.at[0,str(i)]
    alist.append(i)
    
population.columns=alist 


population.drop(population.index[0],axis=0,inplace=True)  #去除第0列
population.head()

,統計年月,區域別代碼,區域別,村里名稱,出生數,出生數-男,出生數-女,死亡數,死亡數-男,死亡數-女,結婚對數_異性,結婚對數_同性,結婚對數_同性_男,結婚對數_同性_女,離婚對數_異性,離婚對數_同性,離婚對數_同性_男,離婚對數_同性_女
1,10911,65000010001,新北市板橋區,留侯里,0,0,0,2,2,0,0,0,0,0,0,0,0,0
2,10911,65000010002,新北市板橋區,流芳里,0,0,0,1,0,1,0,0,0,0,0,0,0,0
3,10911,65000010003,新北市板橋區,赤松里,0,0,0,2,1,1,0,0,0,0,0,0,0,0
4,10911,65000010004,新北市板橋區,黃石里,0,0,0,1,0,1,0,0,0,0,0,0,0,0
5,10911,65000010005,新北市板橋區,挹秀里,5,2,3,3,2,1,0,0,0,0,0,0,0,0

### Solution 1-2

In [66]:
population['出生數']=population['出生數'].astype(int)
population.iloc[:, 4:] = population.iloc[:, 4:].astype(int)
population.dtypes

統計年月         object
區域別代碼        object
區域別          object
村里名稱         object
出生數           int32
出生數-男         int32
出生數-女         int32
死亡數           int32
死亡數-男         int32
死亡數-女         int32
結婚對數_異性       int32
結婚對數_同性       int32
結婚對數_同性_男     int32
結婚對數_同性_女     int32
離婚對數_異性       int32
離婚對數_同性       int32
離婚對數_同性_男     int32
離婚對數_同性_女     int32
dtype: object

<hr style='border-color:brown; border-width:3px'>

## 二、第二大題 (60 %) 
### 2-1. 請連結上內政部人口生育死亡婚姻數據網頁 (點選<a href='https://data.gov.tw/dataset/131138'>這裡</a>)，請下載從 109年 9 月至 110年 8 月共 12 個月份的<u>各村（里）人口統計月報表（含同婚）</u> 資料集。請<font color='red'>連續讀取 12 個月分的資料</font>，存在一個名為`allYearData`的資料框，(注意: 每個資料集被讀取後的第 0 列都是中文名稱，不是數字資料，請處理此問題。)，並請將所有數字轉換為整數型態。(20%)
### 2-2. 完成上一題後，請以`區域別`欄位分群，分群後的名稱是`allYearDataGP`。(10%)
### 2-3. 請將各縣市區的 <font color='red'>出生數</font>和<font color='red'>死亡數</font>加總 (sum)，名稱是 `birth_death`。(10%)
### 2-4. 請找出台南市每個區的<font color='red'>出生數</font>和<font color='red'>死亡數</font>，名稱是`tainan_bd`，並請計算出生和死亡的比例 (出生數/死亡數)，將將結果新增到 `tainan_bd`的一個新欄位，名稱是`出生死亡率`。(20%)

### Solution 2-1

In [156]:
ListMonth=[10909,10910,10911,10912,11001,11002,11003,11004,11005,11006,11007,11008]

allYearData=pd.DataFrame()
    
for i in ListMonth:
    test=pd.read_csv('./data2/opendata{}M013.csv'.format(i))  #合併DataFrame
    allYearData=pd.concat([allYearData, test],axis=0)

allYearData.columns=population.columns                        #欄位名稱更換為中文
allYearData.drop(allYearData.index[0],axis=0,inplace=True)

allYearData['出生數']=allYearData['出生數'].astype(int)        #改整數型態
allYearData.iloc[:, 4:] = allYearData.iloc[:, 4:].astype(int)


print(allYearData.dtypes)
allYearData.head()

統計年月         object
區域別代碼        object
區域別          object
村里名稱         object
出生數           int32
出生數-男         int32
出生數-女         int32
死亡數           int32
死亡數-男         int32
死亡數-女         int32
結婚對數_異性       int32
結婚對數_同性       int32
結婚對數_同性_男     int32
結婚對數_同性_女     int32
離婚對數_異性       int32
離婚對數_同性       int32
離婚對數_同性_男     int32
離婚對數_同性_女     int32
dtype: object

,統計年月,區域別代碼,區域別,村里名稱,出生數,出生數-男,出生數-女,死亡數,死亡數-男,死亡數-女,結婚對數_異性,結婚對數_同性,結婚對數_同性_男,結婚對數_同性_女,離婚對數_異性,離婚對數_同性,離婚對數_同性_男,離婚對數_同性_女
1,10909,65000010001,新北市板橋區,留侯里,1,0,1,3,1,2,1,1,1,0,1,0,0,0
2,10909,65000010002,新北市板橋區,流芳里,0,0,0,1,0,1,0,0,0,0,0,0,0,0
3,10909,65000010003,新北市板橋區,赤松里,0,0,0,1,1,0,0,0,0,0,0,0,0,0
4,10909,65000010004,新北市板橋區,黃石里,0,0,0,0,0,0,1,0,0,0,0,0,0,0
5,10909,65000010005,新北市板橋區,挹秀里,0,0,0,0,0,0,2,0,0,0,1,0,0,0

### Solution 2-2

In [110]:
allYearDataGP=allYearData.groupby('區域別')
allYearDataGP.size()

區域別
南投縣中寮鄉    216
南投縣仁愛鄉    192
南投縣信義鄉    168
南投縣南投市    408
南投縣名間鄉    276
         ...
高雄市阿蓮區    144
高雄市鳥松區     84
高雄市鳳山區    912
高雄市鹽埕區    252
高雄市鼓山區    456
Length: 368, dtype: int64

### Solution 2-3

In [137]:
for GPname in  allYearDataGP.indices.keys():
    birth=allYearDataGP.get_group(GPname).sum()['出生數']
    death=allYearDataGP.get_group(GPname).sum()['死亡數']
    birth_death=birth+death
    print('name: ', GPname)
    print('出生死亡加總: ', birth_death)

name:  南投縣中寮鄉
出生死亡加總:  247
name:  南投縣仁愛鄉
出生死亡加總:  363
name:  南投縣信義鄉
出生死亡加總:  330
name:  南投縣南投市
出生死亡加總:  1395
name:  南投縣名間鄉
出生死亡加總:  597
name:  南投縣國姓鄉
出生死亡加總:  340
name:  南投縣埔里鎮
出生死亡加總:  1251
name:  南投縣水里鄉
出生死亡加總:  328
name:  南投縣竹山鎮
出生死亡加總:  849
name:  南投縣草屯鎮
出生死亡加總:  1558
name:  南投縣集集鎮
出生死亡加總:  202
name:  南投縣魚池鄉
出生死亡加總:  302
name:  南投縣鹿谷鄉
出生死亡加總:  302
name:  嘉義市東區
出生死亡加總:  1548
name:  嘉義市西區
出生死亡加總:  1942
name:  嘉義縣中埔鄉
出生死亡加總:  730
name:  嘉義縣六腳鄉
出生死亡加總:  444
name:  嘉義縣大埔鄉
出生死亡加總:  83
name:  嘉義縣大林鎮
出生死亡加總:  475
name:  嘉義縣太保市
出生死亡加總:  583
name:  嘉義縣布袋鎮
出生死亡加總:  514
name:  嘉義縣新港鄉
出生死亡加總:  515
name:  嘉義縣朴子市
出生死亡加總:  676
name:  嘉義縣東石鄉
出生死亡加總:  458
name:  嘉義縣梅山鄉
出生死亡加總:  347
name:  嘉義縣民雄鄉
出生死亡加總:  986
name:  嘉義縣水上鄉
出生死亡加總:  724
name:  嘉義縣溪口鄉
出生死亡加總:  275
name:  嘉義縣番路鄉
出生死亡加總:  186
name:  嘉義縣竹崎鄉
出生死亡加總:  633
name:  嘉義縣義竹鄉
出生死亡加總:  363
name:  嘉義縣阿里山鄉
出生死亡加總:  122
name:  嘉義縣鹿草鄉
出生死亡加總:  292
name:  基隆市七堵區
出生死亡加總:  726
name:  基隆市中山區
出生死亡加總:  667
name:  基隆市中正區
出生死亡加總:  794
name:  基隆市仁愛區
出生死亡加總:  636
name:  基隆市信義區
出生死亡加總:  706
name:  基隆市安樂區
出生死亡加總:  965
name:  基隆市暖暖區
出生死亡加總:  497
name:  宜蘭縣三星鄉
出生死亡加總:  344
name:  宜蘭縣五結鄉
出生死亡加總:  748
name:  宜蘭縣冬山鄉
出生死亡加總:  831
name:  宜蘭縣南澳鄉
出生死亡加總:  150
name:  宜蘭縣員山鄉
出生死亡加總:  540
name:  宜蘭縣壯圍鄉
出生死亡加總:  399
name:  宜蘭縣大同鄉
出生死亡加總:  127
name:  宜蘭縣宜蘭市
出生死亡加總:  1278
name:  宜蘭縣礁溪鄉
出生死亡加總:  605
name:  宜蘭縣羅東鎮
出生死亡加總:  902
name:  宜蘭縣蘇澳鎮
出生死亡加總:  581
name:  宜蘭縣頭城鎮
出生死亡加總:  514
name:  屏東縣三地門鄉
出生死亡加總:  152
name:  屏東縣九如鄉
出生死亡加總:  353
name:  屏東縣佳冬鄉
出生死亡加總:  358
name:  屏東縣來義鄉
出生死亡加總:  146
name:  屏東縣內埔鄉
出生死亡加總:  806
name:  屏東縣南州鄉
出生死亡加總:  156
name:  屏東縣屏東市
出生死亡加總:  2773
name:  屏東縣崁頂鄉
出生死亡加總:  218
name:  屏東縣恆春鎮
出生死亡加總:  600
name:  屏東縣新園鄉
出生死亡加總:  524
name:  屏東縣新埤鄉
出生死亡加總:  184
name:  屏東縣春日鄉
出生死亡加總:  101
name:  屏東縣東港鎮
出生死亡加總:  604
name:  屏東縣枋寮鄉
出生死亡加總:  409
name:  屏東縣枋山鄉
出生死亡加總:  122
name:  屏東縣林邊鄉
出生死亡加總:  264
name:  屏東縣泰武鄉
出生死亡加總:  87
name:  屏東縣滿州鄉
出生死亡加總:  125
name:  屏東縣潮州鎮
出生死亡加總:  777
name:  屏東縣牡丹鄉
出生死亡加總:  96
name:  屏東縣獅子鄉
出生死亡加總:  100
name:  屏東縣琉球鄉
出生死亡加總:  156
name:  屏東縣瑪家鄉
出生死亡加總:  122
name:  屏東縣竹田鄉
出生死亡加總:  281
name:  屏東縣萬丹鄉
出生死亡加總:  732
name:  屏東縣萬巒鄉
出生死亡加總:  408
name:  屏東縣車城鄉
出生死亡加總:  152
name:  屏東縣里港鄉
出生死亡加總:  462
name:  屏東縣長治鄉
出生死亡加總:  421
name:  屏東縣霧臺鄉
出生死亡加總:  73
name:  屏東縣高樹鄉
出生死亡加總:  525
name:  屏東縣鹽埔鄉
出生死亡加總:  415
name:  屏東縣麟洛鄉
出生死亡加總:  163
name:  彰化縣二林鎮
出生死亡加總:  895
name:  彰化縣二水鄉
出生死亡加總:  327
name:  彰化縣伸港鄉
出生死亡加總:  685
name:  彰化縣北斗鎮
出生死亡加總:  622
name:  彰化縣和美鎮
出生死亡加總:  1474
name:  彰化縣員林市
出生死亡加總:  2033
name:  彰化縣埔心鄉
出生死亡加總:  626
name:  彰化縣埔鹽鄉
出生死亡加總:  605
name:  彰化縣埤頭鄉
出生死亡加總:  624
name:  彰化縣大城鄉
出生死亡加總:  362
name:  彰化縣大村鄉
出生死亡加總:  732
name:  彰化縣彰化市
出生死亡加總:  3677
name:  彰化縣永靖鄉
出生死亡加總:  654
name:  彰化縣溪州鄉
出生死亡加總:  627
name:  彰化縣溪湖鎮
出生死亡加總:  949
name:  彰化縣田中鎮
出生死亡加總:  766
name:  彰化縣田尾鄉
出生死亡加總:  520
name:  彰化縣社頭鄉
出生死亡加總:  784
name:  彰化縣福興鄉
出生死亡加總:  806
name:  彰化縣秀水鄉
出生死亡加總:  636
name:  彰化縣竹塘鄉
出生死亡加總:  355
name:  彰化縣線西鄉
出生死亡加總:  278
name:  彰化縣芬園鄉
出生死亡加總:  488
name:  彰化縣花壇鄉
出生死亡加總:  763
name:  彰化縣芳苑鄉
出生死亡加總:  679
name:  彰化縣鹿港鎮
出生死亡加總:  1465
name:  新北市三峽區
出生死亡加總:  1617
name:  新北市三芝區
出生死亡加總:  320
name:  新北市三重區
出生死亡加總:  5179
name:  新北市中和區
出生死亡加總:  5186
name:  新北市五股區
出生死亡加總:  1226
name:  新北市八里區
出生死亡加總:  537
name:  新北市土城區
出生死亡加總:  2824
name:  新北市坪林區
出生死亡加總:  112
name:  新北市平溪區
出生死亡加總:  98
name:  新北市新店區
出生死亡加總:  3927
name:  新北市新莊區
出生死亡加總:  5327
name:  新北市板橋區
出生死亡加總:  7096
name:  新北市林口區
出生死亡加總:  1564
name:  新北市樹林區
出生死亡加總:  2354
name:  新北市永和區
出生死亡加總:  2602
name:  新北市汐止區
出生死亡加總:  2452
name:  新北市泰山區
出生死亡加總:  931
name:  新北市淡水區
出生死亡加總:  2374
name:  新北市深坑區
出生死亡加總:  281
name:  新北市烏來區
出生死亡加總:  104
name:  新北市瑞芳區
出生死亡加總:  659
name:  新北市石碇區
出生死亡加總:  129
name:  新北市石門區
出生死亡加總:  147
name:  新北市萬里區
出生死亡加總:  390
name:  新北市蘆洲區
出生死亡加總:  2445
name:  新北市貢寮區
出生死亡加總:  191
name:  新北市金山區
出生死亡加總:  299
name:  新北市雙溪區
出生死亡加總:  174
name:  新北市鶯歌區
出生死亡加總:  1221
name:  新竹市北區
出生死亡加總:  2122
name:  新竹市東區
出生死亡加總:  2897
name:  新竹市香山區
出生死亡加總:  1130
name:  新竹縣五峰鄉
出生死亡加總:  130
name:  新竹縣北埔鄉
出生死亡加總:  189
name:  新竹縣寶山鄉
出生死亡加總:  225
name:  新竹縣尖石鄉
出生死亡加總:  245
name:  新竹縣峨眉鄉
出生死亡加總:  114
name:  新竹縣新埔鎮
出生死亡加總:  537
name:  新竹縣新豐鄉
出生死亡加總:  687
name:  新竹縣橫山鄉
出生死亡加總:  231
name:  新竹縣湖口鄉
出生死亡加總:  1073
name:  新竹縣竹北市
出生死亡加總:  2628
name:  新竹縣竹東鎮
出生死亡加總:  1278
name:  新竹縣芎林鄉
出生死亡加總:  348
name:  新竹縣關西鎮
出生死亡加總:  512
name:  桃園市中壢區
出生死亡加總:  6311
name:  桃園市八德區
出生死亡加總:  3400
name:  桃園市大園區
出生死亡加總:  1590
name:  桃園市大溪區
出生死亡加總:  1572
name:  桃園市平鎮區
出生死亡加總:  3438
name:  桃園市復興區
出生死亡加總:  299
name:  桃園市新屋區
出生死亡加總:  878
name:  桃園市桃園區
出生死亡加總:  6165
name:  桃園市楊梅區
出生死亡加總:  2689
name:  桃園市蘆竹區
出生死亡加總:  2265
name:  桃園市觀音區
出生死亡加總:  1129
name:  桃園市龍潭區
出生死亡加總:  1950
name:  桃園市龜山區
出生死亡加總:  2663
name:  澎湖縣七美鄉
出生死亡加總:  94
name:  澎湖縣望安鄉
出生死亡加總:  108
name:  澎湖縣湖西鄉
出生死亡加總:  304
name:  澎湖縣白沙鄉
出生死亡加總:  215
name:  澎湖縣西嶼鄉
出生死亡加總:  199
name:  澎湖縣馬公市
出生死亡加總:  977
name:  臺中市中區
出生死亡加總:  267
name:  臺中市北區
出生死亡加總:  1928
name:  臺中市北屯區
出生死亡加總:  3648
name:  臺中市南區
出生死亡加總:  1534
name:  臺中市南屯區
出生死亡加總:  1975
name:  臺中市后里區
出生死亡加總:  835
name:  臺中市和平區
出生死亡加總:  183
name:  臺中市外埔區
出生死亡加總:  475
name:  臺中市大安區
出生死亡加總:  304
name:  臺中市大甲區
出生死亡加總:  1165
name:  臺中市大肚區
出生死亡加總:  821
name:  臺中市大里區
出生死亡加總:  2615
name:  臺中市大雅區
出生死亡加總:  1252
name:  臺中市太平區
出生死亡加總:  2692
name:  臺中市新社區
出生死亡加總:  403
name:  臺中市東勢區
出生死亡加總:  803
name:  臺中市東區
出生死亡加總:  1042
name:  臺中市梧棲區
出生死亡加總:  808
name:  臺中市沙鹿區
出生死亡加總:  1304
name:  臺中市清水區
出生死亡加總:  1327
name:  臺中市潭子區
出生死亡加總:  1381
name:  臺中市烏日區
出生死亡加總:  1037
name:  臺中市石岡區
出生死亡加總:  223
name:  臺中市神岡區
出生死亡加總:  965
name:  臺中市西區
出生死亡加總:  1309
name:  臺中市西屯區
出生死亡加總:  2651
name:  臺中市豐原區
出生死亡加總:  2259
name:  臺中市霧峰區
出生死亡加總:  952
name:  臺中市龍井區
出生死亡加總:  1014
name:  臺北市中山區
出生死亡加總:  3084
name:  臺北市中正區
出生死亡加總:  2150
name:  臺北市信義區
出生死亡加總:  2987
name:  臺北市內湖區
出生死亡加總:  3598
name:  臺北市北投區
出生死亡加總:  3460
name:  臺北市南港區
出生死亡加總:  1729
name:  臺北市士林區
出生死亡加總:  3925
name:  臺北市大同區
出生死亡加總:  1905
name:  臺北市大安區
出生死亡加總:  3903
name:  臺北市文山區
出生死亡加總:  3635
name:  臺北市松山區
出生死亡加總:  2539
name:  臺北市萬華區
出生死亡加總:  3066
name:  臺南市七股區
出生死亡加總:  401
name:  臺南市下營區
出生死亡加總:  379
name:  臺南市中西區
出生死亡加總:  961
name:  臺南市仁德區
出生死亡加總:  973
name:  臺南市佳里區
出生死亡加總:  801
name:  臺南市六甲區
出生死亡加總:  331
name:  臺南市北區
出生死亡加總:  1630
name:  臺南市北門區
出生死亡加總:  187
name:  臺南市南化區
出生死亡加總:  153
name:  臺南市南區
出生死亡加總:  1690
name:  臺南市善化區
出生死亡加總:  814
name:  臺南市大內區
出生死亡加總:  193
name:  臺南市學甲區
出生死亡加總:  431
name:  臺南市安南區
出生死亡加總:  2545
name:  臺南市安定區
出生死亡加總:  508
name:  臺南市安平區
出生死亡加總:  726
name:  臺南市官田區
出生死亡加總:  319
name:  臺南市將軍區
出生死亡加總:  328
name:  臺南市山上區
出生死亡加總:  157
name:  臺南市左鎮區
出生死亡加總:  115
name:  臺南市後壁區
出生死亡加總:  409
name:  臺南市新化區
出生死亡加總:  640
name:  臺南市新市區
出生死亡加總:  509
name:  臺南市新營區
出生死亡加總:  991
name:  臺南市東區
出生死亡加總:  1951
name:  臺南市東山區
出生死亡加總:  390
name:  臺南市柳營區
出生死亡加總:  363
name:  臺南市楠西區
出生死亡加總:  163
name:  臺南市歸仁區
出生死亡加總:  928
name:  臺南市永康區
出生死亡加總:  2960
name:  臺南市玉井區
出生死亡加總:  231
name:  臺南市白河區
出生死亡加總:  530
name:  臺南市西港區
出生死亡加總:  376
name:  臺南市關廟區
出生死亡加總:  588
name:  臺南市鹽水區
出生死亡加總:  418
name:  臺南市麻豆區
出生死亡加總:  685
name:  臺南市龍崎區
出生死亡加總:  54
name:  臺東縣卑南鄉
出生死亡加總:  315
name:  臺東縣大武鄉
出生死亡加總:  101
name:  臺東縣太麻里鄉
出生死亡加總:  204
name:  臺東縣延平鄉
出生死亡加總:  96
name:  臺東縣成功鎮
出生死亡加總:  249
name:  臺東縣東河鄉
出生死亡加總:  149
name:  臺東縣池上鄉
出生死亡加總:  166
name:  臺東縣海端鄉
出生死亡加總:  95
name:  臺東縣綠島鄉
出生死亡加總:  56
name:  臺東縣臺東市
出生死亡加總:  1642
name:  臺東縣蘭嶼鄉
出生死亡加總:  69
name:  臺東縣達仁鄉
出生死亡加總:  67
name:  臺東縣金峰鄉
出生死亡加總:  59
name:  臺東縣長濱鄉
出生死亡加總:  146
name:  臺東縣關山鎮
出生死亡加總:  159
name:  臺東縣鹿野鄉
出生死亡加總:  140
name:  花蓮縣光復鄉
出生死亡加總:  232
name:  花蓮縣卓溪鄉
出生死亡加總:  148
name:  花蓮縣吉安鄉
出生死亡加總:  1174
name:  花蓮縣壽豐鄉
出生死亡加總:  339
name:  花蓮縣富里鄉
出生死亡加總:  189
name:  花蓮縣新城鄉
出生死亡加總:  338
name:  花蓮縣玉里鎮
出生死亡加總:  446
name:  花蓮縣瑞穗鄉
出生死亡加總:  221
name:  花蓮縣秀林鄉
出生死亡加總:  376
name:  花蓮縣花蓮市
出生死亡加總:  1451
name:  花蓮縣萬榮鄉
出生死亡加總:  128
name:  花蓮縣豐濱鄉
出生死亡加總:  93
name:  花蓮縣鳳林鎮
出生死亡加總:  245
name:  苗栗縣三灣鄉
出生死亡加總:  121
name:  苗栗縣三義鄉
出生死亡加總:  241
name:  苗栗縣公館鄉
出生死亡加總:  458
name:  苗栗縣卓蘭鎮
出生死亡加總:  279
name:  苗栗縣南庄鄉
出生死亡加總:  201
name:  苗栗縣大湖鄉
出生死亡加總:  260
name:  苗栗縣後龍鎮
出生死亡加總:  588
name:  苗栗縣泰安鄉
出生死亡加總:  96
name:  苗栗縣獅潭鄉
出生死亡加總:  109
name:  苗栗縣竹南鎮
出生死亡加總:  1048
name:  苗栗縣苑裡鎮
出生死亡加總:  627
name:  苗栗縣苗栗市
出生死亡加總:  1207
name:  苗栗縣西湖鄉
出生死亡加總:  118
name:  苗栗縣通霄鎮
出生死亡加總:  554
name:  苗栗縣造橋鄉
出生死亡加總:  171
name:  苗栗縣銅鑼鄉
出生死亡加總:  315
name:  苗栗縣頭份市
出生死亡加總:  1432
name:  苗栗縣頭屋鄉
出生死亡加總:  178
name:  連江縣北竿鄉
出生死亡加總:  37
name:  連江縣南竿鄉
出生死亡加總:  103
name:  連江縣東引鄉
出生死亡加總:  14
name:  連江縣莒光鄉
出生死亡加總:  21
name:  金門縣烈嶼鄉
出生死亡加總:  183
name:  金門縣烏坵鄉
出生死亡加總:  7
name:  金門縣金城鎮
出生死亡加總:  595
name:  金門縣金寧鄉
出生死亡加總:  367
name:  金門縣金沙鎮
出生死亡加總:  250
name:  金門縣金湖鎮
出生死亡加總:  401
name:  雲林縣二崙鄉
出生死亡加總:  457
name:  雲林縣元長鄉
出生死亡加總:  462
name:  雲林縣北港鎮
出生死亡加總:  610
name:  雲林縣口湖鄉
出生死亡加總:  446
name:  雲林縣古坑鄉
出生死亡加總:  528
name:  雲林縣四湖鄉
出生死亡加總:  436
name:  雲林縣土庫鎮
出生死亡加總:  457
name:  雲林縣大埤鄉
出生死亡加總:  361
name:  雲林縣崙背鄉
出生死亡加總:  446
name:  雲林縣斗六市
出生死亡加總:  1462
name:  雲林縣斗南鎮
出生死亡加總:  618
name:  雲林縣東勢鄉
出生死亡加總:  285
name:  雲林縣林內鄉
出生死亡加總:  306

name:  雲林縣水林鄉
出生死亡加總:  501
name:  雲林縣臺西鄉
出生死亡加總:  432
name:  雲林縣莿桐鄉
出生死亡加總:  497
name:  雲林縣虎尾鎮
出生死亡加總:  1045
name:  雲林縣褒忠鄉
出生死亡加總:  246
name:  雲林縣西螺鎮
出生死亡加總:  736
name:  雲林縣麥寮鄉
出生死亡加總:  842
name:  高雄市三民區
出生死亡加總:  4531
name:  高雄市仁武區
出生死亡加總:  1430
name:  高雄市內門區
出生死亡加總:  284
name:  高雄市六龜區
出生死亡加總:  268
name:  高雄市前金區
出生死亡加總:  383
name:  高雄市前鎮區
出生死亡加總:  2756
name:  高雄市大寮區
出生死亡加總:  1763
name:  高雄市大樹區
出生死亡加總:  746
name:  高雄市大社區
出生死亡加總:  555
name:  高雄市小港區
出生死亡加總:  2262
name:  高雄市岡山區
出生死亡加總:  1371
name:  高雄市左營區
出生死亡加總:  2507
name:  高雄市彌陀區
出生死亡加總:  316
name:  高雄市新興區
出生死亡加總:  686
name:  高雄市旗山區
出生死亡加總:  653
name:  高雄市旗津區
出生死亡加總:  510
name:  高雄市杉林區
出生死亡加總:  255
name:  高雄市林園區
出生死亡加總:  1160
name:  高雄市桃源區
出生死亡加總:  121
name:  高雄市梓官區
出生死亡加總:  579
name:  高雄市楠梓區
出生死亡加總:  2729
name:  高雄市橋頭區
出生死亡加總:  641
name:  高雄市永安區
出生死亡加總:  254
name:  高雄市湖內區
出生死亡加總:  522
name:  高雄市燕巢區
出生死亡加總:  554
name:  高雄市田寮區
出生死亡加總:  180
name:  高雄市甲仙區
出生死亡加總:  136
name:  高雄市美濃區
出生死亡加總:  740
name:  高雄市苓雅區
出生死亡加總:  2400
name:  高雄市茂林區
出生死亡加總:  37
name:  高雄市茄萣區
出生死亡加總:  537
name:  高雄市路竹區
出生死亡加總:  822
name:  高雄市那瑪夏區
出生死亡加總:  55
name:  高雄市阿蓮區
出生死亡加總:  428
name:  高雄市鳥松區
出生死亡加總:  660
name:  高雄市鳳山區
出生死亡加總:  4962
name:  高雄市鹽埕區
出生死亡加總:  403
name:  高雄市鼓山區
出生死亡加總:  1936

### Solution 2-4

In [164]:
bdList=[]
tainan=pd.DataFrame()
for GPname in allYearDataGP.indices.keys():
    tainanCheck='臺南' in  GPname
    if tainanCheck == True:     
        tainan=tainan+allYearData[allYearData['區域別']==GPname]
        birth=allYearDataGP.get_group(GPname)['出生數']
        death=allYearDataGP.get_group(GPname)['死亡數']
        tainan_bd=birth/death
        for bdData in tainan_bd:
            bdList.append(bdData)
            
    else:
        pass
    
tainan.insert(18, '出生死亡率', bdList)
tainan.head()

,統計年月,區域別代碼,區域別,村里名稱,出生數,出生數-男,出生數-女,死亡數,死亡數-男,死亡數-女,結婚對數_異性,結婚對數_同性,結婚對數_同性_男,結婚對數_同性_女,離婚對數_異性,離婚對數_同性,離婚對數_同性_男,離婚對數_同性_女,出生死亡率,tainan_bd
2618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
2618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN